// Generated by gencpp from file vision/Action.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_ACTION_H
#define VISION_MESSAGE_ACTION_H

#include <ros/service_traits.h>


#include <vision/ActionRequest.h>
#include <vision/ActionResponse.h>


namespace vision
{

struct Action
{

typedef ActionRequest Request;
typedef ActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Action
} // namespace vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision::Action > {
  static const char* value()
  {
    return "48a9460ec0cc64685337f3762768aa1d";
  }

  static const char* value(const ::vision::Action&) { return value(); }
};

template<>
struct DataType< ::vision::Action > {
  static const char* value()
  {
    return "vision/Action";
  }

  static const char* value(const ::vision::Action&) { return value(); }
};


// service_traits::MD5Sum< ::vision::ActionRequest> should match
// service_traits::MD5Sum< ::vision::Action >
template<>
struct MD5Sum< ::vision::ActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision::Action >::value();
  }
  static const char* value(const ::vision::ActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::ActionRequest> should match
// service_traits::DataType< ::vision::Action >
template<>
struct DataType< ::vision::ActionRequest>
{
  static const char* value()
  {
    return DataType< ::vision::Action >::value();
  }
  static const char* value(const ::vision::ActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision::ActionResponse> should match
// service_traits::MD5Sum< ::vision::Action >
template<>
struct MD5Sum< ::vision::ActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision::Action >::value();
  }
  static const char* value(const ::vision::ActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::ActionResponse> should match
// service_traits::DataType< ::vision::Action >
template<>
struct DataType< ::vision::ActionResponse>
{
  static const char* value()
  {
    return DataType< ::vision::Action >::value();
  }
  static const char* value(const ::vision::ActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_MESSAGE_ACTION_H
