// Generated by gencpp from file vision/ActionRequest.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_ACTIONREQUEST_H
#define VISION_MESSAGE_ACTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct ActionRequest_
{
  typedef ActionRequest_<ContainerAllocator> Type;

  ActionRequest_()
    : Action(false)  {
    }
  ActionRequest_(const ContainerAllocator& _alloc)
    : Action(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Action_type;
  _Action_type Action;





  typedef boost::shared_ptr< ::vision::ActionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::ActionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ActionRequest_

typedef ::vision::ActionRequest_<std::allocator<void> > ActionRequest;

typedef boost::shared_ptr< ::vision::ActionRequest > ActionRequestPtr;
typedef boost::shared_ptr< ::vision::ActionRequest const> ActionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::ActionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::ActionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision::ActionRequest_<ContainerAllocator1> & lhs, const ::vision::ActionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Action == rhs.Action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision::ActionRequest_<ContainerAllocator1> & lhs, const ::vision::ActionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision::ActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::ActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::ActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::ActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::ActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::ActionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::ActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9dda7191b6bdf4f8e7537ec0b272b31c";
  }

  static const char* value(const ::vision::ActionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9dda7191b6bdf4f8ULL;
  static const uint64_t static_value2 = 0xe7537ec0b272b31cULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::ActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/ActionRequest";
  }

  static const char* value(const ::vision::ActionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::ActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Action \n"
;
  }

  static const char* value(const ::vision::ActionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::ActionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::ActionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::ActionRequest_<ContainerAllocator>& v)
  {
    s << indent << "Action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_ACTIONREQUEST_H
