// Generated by gencpp from file vision/HarvestResponse.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_HARVESTRESPONSE_H
#define VISION_MESSAGE_HARVESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct HarvestResponse_
{
  typedef HarvestResponse_<ContainerAllocator> Type;

  HarvestResponse_()
    {
    }
  HarvestResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::vision::HarvestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::HarvestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HarvestResponse_

typedef ::vision::HarvestResponse_<std::allocator<void> > HarvestResponse;

typedef boost::shared_ptr< ::vision::HarvestResponse > HarvestResponsePtr;
typedef boost::shared_ptr< ::vision::HarvestResponse const> HarvestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::HarvestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::HarvestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision::HarvestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::HarvestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::HarvestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::HarvestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::HarvestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::HarvestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::HarvestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::vision::HarvestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::HarvestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/HarvestResponse";
  }

  static const char* value(const ::vision::HarvestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::HarvestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::vision::HarvestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::HarvestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HarvestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::HarvestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::vision::HarvestResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_HARVESTRESPONSE_H
