// Generated by gencpp from file vision/ML.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_ML_H
#define VISION_MESSAGE_ML_H

#include <ros/service_traits.h>


#include <vision/MLRequest.h>
#include <vision/MLResponse.h>


namespace vision
{

struct ML
{

typedef MLRequest Request;
typedef MLResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ML
} // namespace vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision::ML > {
  static const char* value()
  {
    return "4972fcc8dd87e24ab9b33086558f9dc5";
  }

  static const char* value(const ::vision::ML&) { return value(); }
};

template<>
struct DataType< ::vision::ML > {
  static const char* value()
  {
    return "vision/ML";
  }

  static const char* value(const ::vision::ML&) { return value(); }
};


// service_traits::MD5Sum< ::vision::MLRequest> should match
// service_traits::MD5Sum< ::vision::ML >
template<>
struct MD5Sum< ::vision::MLRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision::ML >::value();
  }
  static const char* value(const ::vision::MLRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::MLRequest> should match
// service_traits::DataType< ::vision::ML >
template<>
struct DataType< ::vision::MLRequest>
{
  static const char* value()
  {
    return DataType< ::vision::ML >::value();
  }
  static const char* value(const ::vision::MLRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision::MLResponse> should match
// service_traits::MD5Sum< ::vision::ML >
template<>
struct MD5Sum< ::vision::MLResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision::ML >::value();
  }
  static const char* value(const ::vision::MLResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::MLResponse> should match
// service_traits::DataType< ::vision::ML >
template<>
struct DataType< ::vision::MLResponse>
{
  static const char* value()
  {
    return DataType< ::vision::ML >::value();
  }
  static const char* value(const ::vision::MLResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_MESSAGE_ML_H
