// Generated by gencpp from file vision/MLResponse.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_MLRESPONSE_H
#define VISION_MESSAGE_MLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct MLResponse_
{
  typedef MLResponse_<ContainerAllocator> Type;

  MLResponse_()
    : Percentage(0.0)  {
    }
  MLResponse_(const ContainerAllocator& _alloc)
    : Percentage(0.0)  {
  (void)_alloc;
    }



   typedef float _Percentage_type;
  _Percentage_type Percentage;





  typedef boost::shared_ptr< ::vision::MLResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::MLResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MLResponse_

typedef ::vision::MLResponse_<std::allocator<void> > MLResponse;

typedef boost::shared_ptr< ::vision::MLResponse > MLResponsePtr;
typedef boost::shared_ptr< ::vision::MLResponse const> MLResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::MLResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::MLResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision::MLResponse_<ContainerAllocator1> & lhs, const ::vision::MLResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Percentage == rhs.Percentage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision::MLResponse_<ContainerAllocator1> & lhs, const ::vision::MLResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision::MLResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::MLResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::MLResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::MLResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::MLResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::MLResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::MLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "618fd4053c63b8f5b6197bff24518c8d";
  }

  static const char* value(const ::vision::MLResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x618fd4053c63b8f5ULL;
  static const uint64_t static_value2 = 0xb6197bff24518c8dULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::MLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/MLResponse";
  }

  static const char* value(const ::vision::MLResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::MLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 Percentage\n"
"\n"
;
  }

  static const char* value(const ::vision::MLResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::MLResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MLResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::MLResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::MLResponse_<ContainerAllocator>& v)
  {
    s << indent << "Percentage: ";
    Printer<float>::stream(s, indent + "  ", v.Percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_MLRESPONSE_H
