// Generated by gencpp from file vision/Rec.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_REC_H
#define VISION_MESSAGE_REC_H

#include <ros/service_traits.h>


#include <vision/RecRequest.h>
#include <vision/RecResponse.h>


namespace vision
{

struct Rec
{

typedef RecRequest Request;
typedef RecResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Rec
} // namespace vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision::Rec > {
  static const char* value()
  {
    return "524aec0a2d224648b866e7ced15102d4";
  }

  static const char* value(const ::vision::Rec&) { return value(); }
};

template<>
struct DataType< ::vision::Rec > {
  static const char* value()
  {
    return "vision/Rec";
  }

  static const char* value(const ::vision::Rec&) { return value(); }
};


// service_traits::MD5Sum< ::vision::RecRequest> should match
// service_traits::MD5Sum< ::vision::Rec >
template<>
struct MD5Sum< ::vision::RecRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision::Rec >::value();
  }
  static const char* value(const ::vision::RecRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::RecRequest> should match
// service_traits::DataType< ::vision::Rec >
template<>
struct DataType< ::vision::RecRequest>
{
  static const char* value()
  {
    return DataType< ::vision::Rec >::value();
  }
  static const char* value(const ::vision::RecRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision::RecResponse> should match
// service_traits::MD5Sum< ::vision::Rec >
template<>
struct MD5Sum< ::vision::RecResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision::Rec >::value();
  }
  static const char* value(const ::vision::RecResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::RecResponse> should match
// service_traits::DataType< ::vision::Rec >
template<>
struct DataType< ::vision::RecResponse>
{
  static const char* value()
  {
    return DataType< ::vision::Rec >::value();
  }
  static const char* value(const ::vision::RecResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_MESSAGE_REC_H
