// Generated by gencpp from file vision/Recognition_RecResponse.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_RECOGNITION_RECRESPONSE_H
#define VISION_MESSAGE_RECOGNITION_RECRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct Recognition_RecResponse_
{
  typedef Recognition_RecResponse_<ContainerAllocator> Type;

  Recognition_RecResponse_()
    : coordinates()  {
      coordinates.assign(0.0);
  }
  Recognition_RecResponse_(const ContainerAllocator& _alloc)
    : coordinates()  {
  (void)_alloc;
      coordinates.assign(0.0);
  }



   typedef boost::array<float, 4>  _coordinates_type;
  _coordinates_type coordinates;





  typedef boost::shared_ptr< ::vision::Recognition_RecResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::Recognition_RecResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Recognition_RecResponse_

typedef ::vision::Recognition_RecResponse_<std::allocator<void> > Recognition_RecResponse;

typedef boost::shared_ptr< ::vision::Recognition_RecResponse > Recognition_RecResponsePtr;
typedef boost::shared_ptr< ::vision::Recognition_RecResponse const> Recognition_RecResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::Recognition_RecResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::Recognition_RecResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision::Recognition_RecResponse_<ContainerAllocator1> & lhs, const ::vision::Recognition_RecResponse_<ContainerAllocator2> & rhs)
{
  return lhs.coordinates == rhs.coordinates;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision::Recognition_RecResponse_<ContainerAllocator1> & lhs, const ::vision::Recognition_RecResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision::Recognition_RecResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::Recognition_RecResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::Recognition_RecResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::Recognition_RecResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::Recognition_RecResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::Recognition_RecResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::Recognition_RecResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0e2db642e35a0d781e9ef60e0750101";
  }

  static const char* value(const ::vision::Recognition_RecResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0e2db642e35a0d7ULL;
  static const uint64_t static_value2 = 0x81e9ef60e0750101ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::Recognition_RecResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/Recognition_RecResponse";
  }

  static const char* value(const ::vision::Recognition_RecResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::Recognition_RecResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[4] coordinates \n"
"\n"
;
  }

  static const char* value(const ::vision::Recognition_RecResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::Recognition_RecResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.coordinates);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Recognition_RecResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::Recognition_RecResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::Recognition_RecResponse_<ContainerAllocator>& v)
  {
    s << indent << "coordinates[]" << std::endl;
    for (size_t i = 0; i < v.coordinates.size(); ++i)
    {
      s << indent << "  coordinates[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.coordinates[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_RECOGNITION_RECRESPONSE_H
