// Generated by gencpp from file vision/Recognition_Rec.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_RECOGNITION_REC_H
#define VISION_MESSAGE_RECOGNITION_REC_H

#include <ros/service_traits.h>


#include <vision/Recognition_RecRequest.h>
#include <vision/Recognition_RecResponse.h>


namespace vision
{

struct Recognition_Rec
{

typedef Recognition_RecRequest Request;
typedef Recognition_RecResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Recognition_Rec
} // namespace vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision::Recognition_Rec > {
  static const char* value()
  {
    return "524aec0a2d224648b866e7ced15102d4";
  }

  static const char* value(const ::vision::Recognition_Rec&) { return value(); }
};

template<>
struct DataType< ::vision::Recognition_Rec > {
  static const char* value()
  {
    return "vision/Recognition_Rec";
  }

  static const char* value(const ::vision::Recognition_Rec&) { return value(); }
};


// service_traits::MD5Sum< ::vision::Recognition_RecRequest> should match
// service_traits::MD5Sum< ::vision::Recognition_Rec >
template<>
struct MD5Sum< ::vision::Recognition_RecRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision::Recognition_Rec >::value();
  }
  static const char* value(const ::vision::Recognition_RecRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::Recognition_RecRequest> should match
// service_traits::DataType< ::vision::Recognition_Rec >
template<>
struct DataType< ::vision::Recognition_RecRequest>
{
  static const char* value()
  {
    return DataType< ::vision::Recognition_Rec >::value();
  }
  static const char* value(const ::vision::Recognition_RecRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision::Recognition_RecResponse> should match
// service_traits::MD5Sum< ::vision::Recognition_Rec >
template<>
struct MD5Sum< ::vision::Recognition_RecResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision::Recognition_Rec >::value();
  }
  static const char* value(const ::vision::Recognition_RecResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::Recognition_RecResponse> should match
// service_traits::DataType< ::vision::Recognition_Rec >
template<>
struct DataType< ::vision::Recognition_RecResponse>
{
  static const char* value()
  {
    return DataType< ::vision::Recognition_Rec >::value();
  }
  static const char* value(const ::vision::Recognition_RecResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_MESSAGE_RECOGNITION_REC_H
