// Generated by gencpp from file vision/RecRequest.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_RECREQUEST_H
#define VISION_MESSAGE_RECREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/CompressedImage.h>
#include <sensor_msgs/CompressedImage.h>

namespace vision
{
template <class ContainerAllocator>
struct RecRequest_
{
  typedef RecRequest_<ContainerAllocator> Type;

  RecRequest_()
    : left_Img()
    , right_Img()  {
    }
  RecRequest_(const ContainerAllocator& _alloc)
    : left_Img(_alloc)
    , right_Img(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _left_Img_type;
  _left_Img_type left_Img;

   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _right_Img_type;
  _right_Img_type right_Img;





  typedef boost::shared_ptr< ::vision::RecRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::RecRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RecRequest_

typedef ::vision::RecRequest_<std::allocator<void> > RecRequest;

typedef boost::shared_ptr< ::vision::RecRequest > RecRequestPtr;
typedef boost::shared_ptr< ::vision::RecRequest const> RecRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::RecRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::RecRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision::RecRequest_<ContainerAllocator1> & lhs, const ::vision::RecRequest_<ContainerAllocator2> & rhs)
{
  return lhs.left_Img == rhs.left_Img &&
    lhs.right_Img == rhs.right_Img;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision::RecRequest_<ContainerAllocator1> & lhs, const ::vision::RecRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision::RecRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::RecRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::RecRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::RecRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::RecRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::RecRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::RecRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e217f270e4c39c7cd696ab11a0bcae77";
  }

  static const char* value(const ::vision::RecRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe217f270e4c39c7cULL;
  static const uint64_t static_value2 = 0xd696ab11a0bcae77ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::RecRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/RecRequest";
  }

  static const char* value(const ::vision::RecRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::RecRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/CompressedImage left_Img\n"
"sensor_msgs/CompressedImage right_Img\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/CompressedImage\n"
"# This message contains a compressed image\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"\n"
"string format        # Specifies the format of the data\n"
"                     #   Acceptable values:\n"
"                     #     jpeg, png\n"
"uint8[] data         # Compressed image buffer\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::vision::RecRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::RecRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_Img);
      stream.next(m.right_Img);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::RecRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::RecRequest_<ContainerAllocator>& v)
  {
    s << indent << "left_Img: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.left_Img);
    s << indent << "right_Img: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.right_Img);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_RECREQUEST_H
