// Generated by gencpp from file vision/RepositionRequest.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_REPOSITIONREQUEST_H
#define VISION_MESSAGE_REPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace vision
{
template <class ContainerAllocator>
struct RepositionRequest_
{
  typedef RepositionRequest_<ContainerAllocator> Type;

  RepositionRequest_()
    : Location()  {
    }
  RepositionRequest_(const ContainerAllocator& _alloc)
    : Location(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _Location_type;
  _Location_type Location;





  typedef boost::shared_ptr< ::vision::RepositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::RepositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RepositionRequest_

typedef ::vision::RepositionRequest_<std::allocator<void> > RepositionRequest;

typedef boost::shared_ptr< ::vision::RepositionRequest > RepositionRequestPtr;
typedef boost::shared_ptr< ::vision::RepositionRequest const> RepositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::RepositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::RepositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision::RepositionRequest_<ContainerAllocator1> & lhs, const ::vision::RepositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Location == rhs.Location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision::RepositionRequest_<ContainerAllocator1> & lhs, const ::vision::RepositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision::RepositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::RepositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::RepositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::RepositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::RepositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::RepositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::RepositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42bda7d7fa622f066e545e9d3f38c04e";
  }

  static const char* value(const ::vision::RepositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42bda7d7fa622f06ULL;
  static const uint64_t static_value2 = 0x6e545e9d3f38c04eULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::RepositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/RepositionRequest";
  }

  static const char* value(const ::vision::RepositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::RepositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"geometry_msgs/Vector3 Location \n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::vision::RepositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::RepositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RepositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::RepositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::RepositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "Location: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.Location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_REPOSITIONREQUEST_H
