// Generated by gencpp from file vision/Stereo_Rec.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_STEREO_REC_H
#define VISION_MESSAGE_STEREO_REC_H

#include <ros/service_traits.h>


#include <vision/Stereo_RecRequest.h>
#include <vision/Stereo_RecResponse.h>


namespace vision
{

struct Stereo_Rec
{

typedef Stereo_RecRequest Request;
typedef Stereo_RecResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Stereo_Rec
} // namespace vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision::Stereo_Rec > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::vision::Stereo_Rec&) { return value(); }
};

template<>
struct DataType< ::vision::Stereo_Rec > {
  static const char* value()
  {
    return "vision/Stereo_Rec";
  }

  static const char* value(const ::vision::Stereo_Rec&) { return value(); }
};


// service_traits::MD5Sum< ::vision::Stereo_RecRequest> should match
// service_traits::MD5Sum< ::vision::Stereo_Rec >
template<>
struct MD5Sum< ::vision::Stereo_RecRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision::Stereo_Rec >::value();
  }
  static const char* value(const ::vision::Stereo_RecRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::Stereo_RecRequest> should match
// service_traits::DataType< ::vision::Stereo_Rec >
template<>
struct DataType< ::vision::Stereo_RecRequest>
{
  static const char* value()
  {
    return DataType< ::vision::Stereo_Rec >::value();
  }
  static const char* value(const ::vision::Stereo_RecRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision::Stereo_RecResponse> should match
// service_traits::MD5Sum< ::vision::Stereo_Rec >
template<>
struct MD5Sum< ::vision::Stereo_RecResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision::Stereo_Rec >::value();
  }
  static const char* value(const ::vision::Stereo_RecResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::Stereo_RecResponse> should match
// service_traits::DataType< ::vision::Stereo_Rec >
template<>
struct DataType< ::vision::Stereo_RecResponse>
{
  static const char* value()
  {
    return DataType< ::vision::Stereo_Rec >::value();
  }
  static const char* value(const ::vision::Stereo_RecResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_MESSAGE_STEREO_REC_H
