// Generated by gencpp from file vision/Take_Img.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_TAKE_IMG_H
#define VISION_MESSAGE_TAKE_IMG_H

#include <ros/service_traits.h>


#include <vision/Take_ImgRequest.h>
#include <vision/Take_ImgResponse.h>


namespace vision
{

struct Take_Img
{

typedef Take_ImgRequest Request;
typedef Take_ImgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Take_Img
} // namespace vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vision::Take_Img > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::vision::Take_Img&) { return value(); }
};

template<>
struct DataType< ::vision::Take_Img > {
  static const char* value()
  {
    return "vision/Take_Img";
  }

  static const char* value(const ::vision::Take_Img&) { return value(); }
};


// service_traits::MD5Sum< ::vision::Take_ImgRequest> should match
// service_traits::MD5Sum< ::vision::Take_Img >
template<>
struct MD5Sum< ::vision::Take_ImgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vision::Take_Img >::value();
  }
  static const char* value(const ::vision::Take_ImgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::Take_ImgRequest> should match
// service_traits::DataType< ::vision::Take_Img >
template<>
struct DataType< ::vision::Take_ImgRequest>
{
  static const char* value()
  {
    return DataType< ::vision::Take_Img >::value();
  }
  static const char* value(const ::vision::Take_ImgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vision::Take_ImgResponse> should match
// service_traits::MD5Sum< ::vision::Take_Img >
template<>
struct MD5Sum< ::vision::Take_ImgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vision::Take_Img >::value();
  }
  static const char* value(const ::vision::Take_ImgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vision::Take_ImgResponse> should match
// service_traits::DataType< ::vision::Take_Img >
template<>
struct DataType< ::vision::Take_ImgResponse>
{
  static const char* value()
  {
    return DataType< ::vision::Take_Img >::value();
  }
  static const char* value(const ::vision::Take_ImgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISION_MESSAGE_TAKE_IMG_H
