// Generated by gencpp from file vision/Take_ImgRequest.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_TAKE_IMGREQUEST_H
#define VISION_MESSAGE_TAKE_IMGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct Take_ImgRequest_
{
  typedef Take_ImgRequest_<ContainerAllocator> Type;

  Take_ImgRequest_()
    {
    }
  Take_ImgRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::vision::Take_ImgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::Take_ImgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Take_ImgRequest_

typedef ::vision::Take_ImgRequest_<std::allocator<void> > Take_ImgRequest;

typedef boost::shared_ptr< ::vision::Take_ImgRequest > Take_ImgRequestPtr;
typedef boost::shared_ptr< ::vision::Take_ImgRequest const> Take_ImgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::Take_ImgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::Take_ImgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision::Take_ImgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::Take_ImgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::Take_ImgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::Take_ImgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::Take_ImgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::Take_ImgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::Take_ImgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::vision::Take_ImgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::Take_ImgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/Take_ImgRequest";
  }

  static const char* value(const ::vision::Take_ImgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::Take_ImgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::vision::Take_ImgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::Take_ImgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Take_ImgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::Take_ImgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::vision::Take_ImgRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_TAKE_IMGREQUEST_H
