(cl:defpackage vision-srv
  (:use )
  (:export
   "ACTION"
   "<ACTION-REQUEST>"
   "ACTION-REQUEST"
   "<ACTION-RESPONSE>"
   "ACTION-RESPONSE"
   "REPOSITION"
   "<REPOSITION-REQUEST>"
   "REPOSITION-REQUEST"
   "<REPOSITION-RESPONSE>"
   "REPOSITION-RESPONSE"
  ))

